Home banners
SofiaCantero24/BlackMarket pull request #16
Opened 2024-12-04 15:54 UTC by SofiaCantero24

## What does this do?
Home banners

![simulator_screenshot_9ABB6D97-8B99-4488-9284-8CC59319C6C1](https://github.com/user-attachments/assets/932417e6-2a02-4fe8-8151-f5ee1c71de42)

## Notion Ticket
* [Home Banners](https://www.notion.so/rootstrap/Dashboard-banners-f6bb59b35b744386aa607b014b11de19?pvs=4)

## Figma view
* [Home screen](https://www.figma.com/file/uUWXfDpuvDtnOHdSRjv0t1/Black-Market---iOS?type=design&node-id=4-720&mode=design&t=sIzqiHFLhyenWELW-4)

## Why did you do this?

## Who/what does this impact?

## How did you test this?

2024-12-04 19:13 UTC, fernandatoledo requested changes
Importing media files directly for this purpose is not ideal for several reasons:

**Accessibility**: Images with embedded text often fail to meet accessibility standards, such as providing proper alternative text or being screen-reader friendly.

**Localization**: If the app supports multiple languages, each language would require its own set of images, which is not scalable or maintainable.

A more robust solution would be to create a reusable component for these banners. The component could take an image (or background color) as a prop, a variant to determine its layout (e.g., left or right alignment), and children for the text content. This structure allows you to manage styles, accessibility, and localization effectively.

2024-12-05 14:18 UTC, juanchoperezj approved these changes

2024-12-09 16:15 UTC, fernandatoledo approved these changes

2024-12-09 16:15 UTC, fernandatoledo commented on assets/fedex-ad.png
Remove unnecessary file

2024-12-09 19:13 UTC, merged